fix(internal): improve git log for commits on current branch since last release
Nightapes/go-semantic-release pull request #69
Opened 2021-04-27 19:38 UTC by Nightapes

At the moment when PRs where done in parallel it could happen that some commits where ignored in the release. This should be fixed now

2021-04-27 20:58 UTC, fwiedmann requested changes

2021-04-27 20:58 UTC, fwiedmann commented on internal/gitutil/gitutil.go
> +	}
startCommit is used at line 155. I suggest moving an initialization near as possible to the caller.

2021-04-27 20:58 UTC, fwiedmann commented on internal/gitutil/gitutil.go
>  	}
I suggest initializing the `ref` near as possible to the caller.

2021-04-28 06:36 UTC, Nightapes commented
@fwiedmann code is updated

2021-04-28 06:43 UTC, merged